# Generated by Django 5.0.2 on 2024-06-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0003_remove_recipe_author_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
