# Generated by Django 5.0.2 on 2024-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
