# Generated by Django 5.0.2 on 2024-06-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapi', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
